name: Test - Publish

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: make test

      - name: Publish package
        run: |
          echo "Running commands based on branch: ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" == "master"* ]]; then
            echo "Deploy package with manual release"
            ./gradlew publishToMavenCentral --no-configuration-cache
          elif [[ "${{ github.ref_name }}" == "releases"* ]]; then
            echo "Deploy package with automatic release"
            ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
          else
            echo "No specific commands for this branch"
          fi
        env: 
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}